modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "${mod_url}"
authors="${mod_author}"
description = "GregTech Leisure Core Mods"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "gtceu"
mandatory = true
versionRange = "[${gtceu_version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "ae2"
mandatory = true
versionRange = "[15.2.,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "ad_astra"
mandatory = true
versionRange = "[${ad_astra_version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "gtmthings"
mandatory = true
versionRange = "[1.3,)"
ordering = "AFTER"
side = "BOTH"
